# Generated by Django 2.1 on 2019-06-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('second', models.CharField(max_length=200)),
                ('birth_date', models.DateTimeField()),
                ('city', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('img', models.ImageField(blank=True, null=True, upload_to='src/media')),
                ('name', models.CharField(default='Имя', max_length=200)),
                ('second', models.CharField(default='Фамилия', max_length=200)),
                ('birth_date', models.DateField(auto_now_add=True)),
                ('city', models.CharField(default='Липецк', max_length=300)),
            ],
        ),
    ]
