# Generated by Django 2.1 on 2019-06-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='birth_date',
            field=models.DateField(blank=True),
        ),
    ]
