# Generated by Django 2.1 on 2019-06-18 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_summary_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
